# Project 1: Global Supply Chain & Demand Intelligence Hub
## Phase 1: Python Cleaning & Feature Engineering
### Objective
Clean Olist datasets, merge required tables, and create business features.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

## Load Datasets
Reading all Olist CSV files into Pandas DataFrames.

In [4]:
# Read all CSV files

orders = pd.read_csv('D:\Resume Projects\supply-chain-analytics-pipeline\Dataset\olist_orders_dataset.csv')
order_items = pd.read_csv('D:\Resume Projects\supply-chain-analytics-pipeline\Dataset\olist_order_items_dataset.csv')
order_payments = pd.read_csv('D:\Resume Projects\supply-chain-analytics-pipeline\Dataset\olist_order_payments_dataset.csv')
customers = pd.read_csv('D:\Resume Projects\supply-chain-analytics-pipeline\Dataset\olist_customers_dataset.csv')
products = pd.read_csv('D:\Resume Projects\supply-chain-analytics-pipeline\Dataset\olist_products_dataset.csv')
sellers = pd.read_csv('D:\Resume Projects\supply-chain-analytics-pipeline\Dataset\olist_sellers_dataset.csv')
geolocation = pd.read_csv('D:\Resume Projects\supply-chain-analytics-pipeline\Dataset\olist_geolocation_dataset.csv')
order_reviews = pd.read_csv('D:\Resume Projects\supply-chain-analytics-pipeline\Dataset\olist_order_reviews_dataset.csv')

## Initial Data Inspection
Checking dataset shape, columns, datatypes, and sample records.

In [6]:
# Check shape of all datasets

print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Payments:", order_payments.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Geolocation:", geolocation.shape)
print("Reviews:", order_reviews.shape)

Orders: (99441, 8)
Order Items: (112650, 7)
Payments: (103886, 5)
Customers: (99441, 5)
Products: (32951, 9)
Sellers: (3095, 4)
Geolocation: (1000163, 5)
Reviews: (99224, 7)

In [7]:
# Preview datasets

orders.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00

In [8]:
# Preview Dataset
customers.head(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
5,879864dab9bc3047522c92c82e1212b8,4c93744516667ad3b8f1fb645a3116a4,89254,jaragua do sul,SC
6,fd826e7cf63160e536e0908c76c3f441,addec96d2e059c80c30fe6871d30d177,4534,sao paulo,SP
7,5e274e7a0c3809e14aba7ad5aae0d407,57b2a98a409812fe9618067b6b8ebe4f,35182,timoteo,MG
8,5adf08e34b2e993982a47070956c5c65,1175e95fb47ddff9de6b2b06188f7e0d,81560,curitiba,PR
9,4b7139f34592b3a31687243a302fa75b,9afe194fb833f79e300e37e580171f22,30575,belo horizonte,MG

In [9]:
# Preview Dataset
products.head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0

In [10]:
# Preview Dataset
order_items.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,2017-05-23 03:55:27,21.90,12.69
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,2017-12-14 12:10:31,19.90,11.85
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,2018-03-26 18:31:29,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,2018-07-06 14:10:56,53.99,11.40

In [11]:
# Preview Dataset Structure
datasets = {
    "orders": orders,
    "order_items": order_items,
    "order_payments": order_payments,
    "customers": customers,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "order_reviews": order_reviews
}

for name, df in datasets.items():
    print(f"\n--- {name.upper()} ---")
    df.info()

--- ORDERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

--- ORDER_ITEMS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

--- ORDER_PAYMENTS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

--- CUSTOMERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

--- PRODUCTS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

--- SELLERS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

--- GEOLOCATION ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

--- ORDER_REVIEWS ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [12]:
# Check null Values
for name, df in datasets.items():
    print(f"\n--- {name.upper()} NULL VALUES ---")
    print(df.isnull().sum())

--- ORDERS NULL VALUES ---
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

--- ORDER_ITEMS NULL VALUES ---
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

--- ORDER_PAYMENTS NULL VALUES ---
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

--- CUSTOMERS NULL VALUES ---
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

--- PRODUCTS NULL VALUES ---
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

--- SELLERS NULL VALUES ---
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

--- GEOLOCATION NULL VALUES ---
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

--- ORDER_REVIEWS NULL VALUES ---
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [13]:
# Check the duplicates
for name, df in datasets.items():
    print(f"\n--- {name.upper()} DUPLICATES ---")
    print(df.duplicated().sum())

--- ORDERS DUPLICATES ---
0

--- ORDER_ITEMS DUPLICATES ---
0

--- ORDER_PAYMENTS DUPLICATES ---
0

--- CUSTOMERS DUPLICATES ---
0

--- PRODUCTS DUPLICATES ---
0

--- SELLERS DUPLICATES ---
0

--- GEOLOCATION DUPLICATES ---
261831

--- ORDER_REVIEWS DUPLICATES ---
0

## Datatype Conversion
Converting date columns from object datatype to datetime format for time-based analysis and feature engineering.

In [14]:
# Orders dataset datetime conversion

orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp'])

orders['order_approved_at'] = pd.to_datetime(
    orders['order_approved_at'])

orders['order_delivered_carrier_date'] = pd.to_datetime(
    orders['order_delivered_carrier_date'])

orders['order_delivered_customer_date'] = pd.to_datetime(
    orders['order_delivered_customer_date'])

orders['order_estimated_delivery_date'] = pd.to_datetime(
    orders['order_estimated_delivery_date'])

# Order Items dataset datetime conversion

order_items['shipping_limit_date'] = pd.to_datetime(
    order_items['shipping_limit_date'])

# Order Reviews dataset datetime conversion

order_reviews['review_creation_date'] = pd.to_datetime(
    order_reviews['review_creation_date'])

order_reviews['review_answer_timestamp'] = pd.to_datetime(
    order_reviews['review_answer_timestamp'])

In [15]:
# Verify datatype conversion

orders.info()

order_items.info()

order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 6.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  datetime64[ns]
 6   review_answer_timestamp  99224 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 5.3+ MB

## Duplicate Handling

Removing exact duplicate rows from the geolocation dataset to reduce redundant location records and improve query performance.

In [16]:
# Remove exact duplicate rows from geolocation dataset
geolocation = geolocation.drop_duplicates()

# Verify duplicate removal
print("Remaining duplicates:",
      geolocation.duplicated().sum())

Remaining duplicates: 0

## Null Value Handling

Handling missing values in the products dataset to maintain data consistency and avoid null values during analysis and dashboard creation.

In [17]:
# Fill missing product category names

products['product_category_name'] = (
    products['product_category_name']
    .fillna('Unknown')
)

# Fill numeric null values with median

products['product_name_lenght'] = (
    products['product_name_lenght']
    .fillna(products['product_name_lenght'].median())
)

products['product_description_lenght'] = (
    products['product_description_lenght']
    .fillna(products['product_description_lenght'].median())
)

products['product_photos_qty'] = (
    products['product_photos_qty']
    .fillna(products['product_photos_qty'].median())
)

products['product_weight_g'] = (
    products['product_weight_g']
    .fillna(products['product_weight_g'].median())
)

products['product_length_cm'] = (
    products['product_length_cm']
    .fillna(products['product_length_cm'].median())
)

products['product_height_cm'] = (
    products['product_height_cm']
    .fillna(products['product_height_cm'].median())
)

products['product_width_cm'] = (
    products['product_width_cm']
    .fillna(products['product_width_cm'].median())
)

# Verify null values
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

## Feature Engineering

Creating business features for sales, delivery, and operational analysis.

### Delivery Delay
Calculating the difference between actual delivery date and estimated delivery date to measure late or early delivery.

In [23]:
# Delivery delay in days
orders['delivery_delay'] = (
    orders['order_delivered_customer_date'] - orders['order_estimated_delivery_date']
).dt.days

### Lead Time
Calculating the number of days taken from purchase to final delivery.

In [24]:
# Lead time in days
orders['lead_time'] = (
    orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']
).dt.days

### Total Sales
Creating total sales per order item using product price and freight value.

In [25]:
# Total sales per order item
order_items['total_sales'] = order_items['price'] + order_items['freight_value']

### Purchase Year
Extracting the year from the order purchase timestamp.

In [26]:
# Purchase year
orders['purchase_year'] = orders['order_purchase_timestamp'].dt.year

### Purchase Month
Extracting the month from the order purchase timestamp.

In [27]:
# Purchase month
orders['purchase_month'] = orders['order_purchase_timestamp'].dt.month

### Purchase Day
Extracting the day from the order purchase timestamp.

In [28]:
# Purchase day
orders['purchase_day'] = orders['order_purchase_timestamp'].dt.day

### Purchase Hour
Extracting the hour from the order purchase timestamp to analyze peak ordering time.

In [29]:
# Purchase hour
orders['purchase_hour'] = orders['order_purchase_timestamp'].dt.hour

## Dataset Relationships and Merge Preparation

Identifying primary and foreign keys across datasets and testing joins to prepare analytical datasets for SQL warehouse modeling and downstream analytics.

### Display Important Join Keys

In [30]:
# Important join keys across datasets

print("Orders Keys:")
print(orders[['order_id', 'customer_id']].head())

print("\nOrder Items Keys:")
print(order_items[['order_id', 'product_id', 'seller_id']].head())

print("\nCustomers Keys:")
print(customers[['customer_id']].head())

print("\nProducts Keys:")
print(products[['product_id']].head())

print("\nSellers Keys:")
print(sellers[['seller_id']].head())

Orders Keys:
                           order_id                       customer_id
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

Order Items Keys:
                           order_id                        product_id  \
0  00010242fe8c5a6d1ba2dd792cb16214  4244733e06e7ecb4970a6e2683c13e61
1  00018f77f2f0320c557190d7a144bdd3  e5f2d52b802189ee658865ca93d83a8f
2  000229ec398224ef6ca0657da4fc703e  c777355d18b72b67abbeef9df44fd0fd
3  00024acbcdf0a6daa1e931b038114c75  7634da152a4610f1595efa32f14722fc
4  00042b26cf59d7ce69dfabb4e55b4fd9  ac6c3623068f30de03045865e4e10089

                          seller_id
0  48436dade18ac8b2bce089ec2a041202
1  dd7ddc04e1b6c2c614352b383efe2d36
2  5b51032eddd242adc84c38acab88f23d
3  9d7a1d34a5052409006425275ba1c2b4
4  df560393f3a51e74553ab94004ba5c87

Customers Keys:
                        customer_id
0  06b8999e2fba1a1fbc88172c00ba8bc7
1  18955e83d337fd6b2def6b18a428ac77
2  4e7b3e00288586ebd08712fdd0374a03
3  b2b6027bc5c5109e529d4dc6358b12c3
4  4f2d8ab171c80ec8364f7c12e35b23ad

Products Keys:
                         product_id
0  1e9e8ef04dbcff4541ed26657ea517e5
1  3aa071139cb16b67ca9e5dea641aaa2f
2  96bd76ec8810374ed1b65e291975717f
3  cef67bcfe19066a932b7673e239eb23d
4  9dc1a7de274444849c219cff195d0b71

Sellers Keys:
                          seller_id
0  3442f8959a84dea7ee197c632cb2df15
1  d1b65fc7debc3361ea86b5f14c68d2e2
2  ce3ad9de960102d0677a81f5d0bb7b2d
3  c0f3eea2e14555b6faeea3dd58c1b1c3
4  51a04a8a6bdcb23deccc82b0b80742cf

### Testing Dataset Relationships
Performing sample joins between datasets to validate relationships and prepare for analytical modeling.

In [31]:
# Merge orders and order_items

orders_items_merged = orders.merge(
    order_items,
    on='order_id',
    how='inner'
)

# Check merged dataset
orders_items_merged.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay,lead_time,...,purchase_month,purchase_day,purchase_hour,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_sales
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8.0,8.0,...,10,2,10,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6.0,13.0,...,7,24,20,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18.0,9.0,...,8,8,8,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13.0,13.0,...,11,18,19,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10.0,2.0,...,2,13,21,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,28.62

In [40]:
# Shape after merge

print("Orders Shape:", orders.shape)
print("Order Items Shape:", order_items.shape)

print("Merged Shape:", orders_items_merged.shape)

Orders Shape: (99441, 14)
Order Items Shape: (112650, 8)
Merged Shape: (112650, 21)

## Merged Dataset Quality Check
Checking null values, duplicates, and basic structure of the merged orders-items dataset before moving to further analysis and modeling.

In [33]:
# Null values in merged dataset
print(orders_items_merged.isnull().sum())

# Duplicate rows in merged dataset
print("\nDuplicate rows:", orders_items_merged.duplicated().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1194
order_delivered_customer_date    2454
order_estimated_delivery_date       0
delivery_delay                   2454
lead_time                        2454
purchase_year                       0
purchase_month                      0
purchase_day                        0
purchase_hour                       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
total_sales                         0
dtype: int64

Duplicate rows: 0

In [34]:
# Shape and column preview
print("Merged Shape:", orders_items_merged.shape)
print("\nColumns:")
print(orders_items_merged.columns.tolist())

Merged Shape: (112650, 21)

Columns:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'delivery_delay', 'lead_time', 'purchase_year', 'purchase_month', 'purchase_day', 'purchase_hour', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'total_sales']

# Push Cleaned Data into MySQL
Loading the cleaned Olist datasets into MySQL as separate staging tables for warehouse modeling, SQL analysis, and downstream ML and Power BI use.

In [37]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from urllib.parse import quote_plus


# MySQL database connection configuration

load_dotenv(dotenv_path="D:\Resume Projects\supply-chain-analytics-pipeline\.env")  #load .env file

user     = os.getenv("DB_USER")
password = quote_plus(os.getenv("DB_PASSWORD"))
host     = os.getenv("DB_HOST")
port     = os.getenv("DB_PORT")
database = os.getenv("DB_NAME")

# Create engine
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

In [38]:
# Push cleaned tables separately to MySQL

orders.to_sql('orders', con=engine, if_exists='replace', index=False)
order_items.to_sql('order_items', con=engine, if_exists='replace', index=False)
order_payments.to_sql('order_payments', con=engine, if_exists='replace', index=False)
customers.to_sql('customers', con=engine, if_exists='replace', index=False)
products.to_sql('products', con=engine, if_exists='replace', index=False)
sellers.to_sql('sellers', con=engine, if_exists='replace', index=False)
geolocation.to_sql('geolocation', con=engine, if_exists='replace', index=False)
order_reviews.to_sql('order_reviews', con=engine, if_exists='replace', index=False)

print("All cleaned tables pushed to MySQL successfully.")

All cleaned tables pushed to MySQL successfully.

In [39]:
# Verify table names in MySQL
pd.read_sql("SHOW TABLES;", con=engine)

  Tables_in_supply_chain_dw
0                 customers
1               geolocation
2               order_items
3            order_payments
4             order_reviews
5                    orders
6                  products
7                   sellers